const RAW_SEED_POSTS = [
    // --- CAREER / WORK (20) ---
    { content: "Gaji UMR tapi gaya hidup SCBD, akhirnya terlilit pinjol... tolongin gue.", topic: "Karir", gender: "M", occupation: "Karyawan Swasta" },
    { content: "Capek banget jadi sandwich generation. Gaji lewat doang buat bayar utang orang tua.", topic: "Keluarga", gender: "F", occupation: "Karyawan" },
    { content: "Baru resign tapi belum dapet kerjaan baru. Deg-degan tiap liat sisa saldo.", topic: "Karir", gender: "M", occupation: "Unemployed" },
    { content: "Bos gue toxic banget, nelpon jam 11 malem cuma buat nanya hal sepele!", topic: "Karir", gender: "F", occupation: "Sekretaris" },
    { content: "Lagi mikir mau banting setir jadi petani aja di kampung. Jakarta jahat.", topic: "Karir", gender: "M", occupation: "IT Support" },
    { content: "Interview udah 5x tapi di-ghosting HRD terus. Apa gue seburuk itu?", topic: "Karir", gender: "NB", occupation: "Fresh Graduate" },
    { content: "Dapet promosi tapi gaji cuma naik 500 ribu. Worth it gak sih beban kerjanya?", topic: "Karir", gender: "M", occupation: "Supervisor" },
    { content: "Temen kantor muka dua semua. Di depan baik, di belakang ngejelekin.", topic: "Karir", gender: "F", occupation: "Admin" },
    { content: "Pengen usaha sendiri tapi takut gagal dan gak punya modal.", topic: "Karir", gender: "M", occupation: "Karyawan" },
    { content: "Burnout parah. Tiap pagi rasanya pengen nangis pas mau berangkat kerja.", topic: "Kesehatan Mental", gender: "F", occupation: "Desainer Grafis" },
    { content: "Gue curiga rekan kerja gue korupsi uang kas kecil, tapi takut lapor.", topic: "Karir", gender: "F", occupation: "Finance" },
    { content: "HRD nanya 'kenapa resign?' padahal satu kantor tau bosnya gila.", topic: "Karir", gender: "M", occupation: "Marketing" },
    { content: "Lagi diem-diem lamar kerja pas jam kantor. Doain lolos ya guys.", topic: "Karir", gender: "F", occupation: "CS" },
    { content: "Meeting 3 jam cuma buat mutusin warna tombol. Buang waktu.", topic: "Karir", gender: "M", occupation: "Product Manager" },
    { content: "Gaji gede tapi gak punya life. Pulang jam 10 malem tiap hari.", topic: "Karir", gender: "M", occupation: "Konsultan" },
    { content: "Baru sadar gue dibayar lebih rendah dari anak baru. Sakit hati.", topic: "Karir", gender: "F", occupation: "Senior Staff" },
    { content: "Diterima kerja di perusahaan impian, tapi ternyata jobdesc-nya palugada.", topic: "Karir", gender: "NB", occupation: "Content Creator" },
    { content: "Pengen resign tapi cicilan KPR masih 15 tahun lagi.", topic: "Karir", gender: "M", occupation: "Manager" },
    { content: "Buka LinkedIn isinya orang pamer achievement semua. Gue kapan?", topic: "Karir", gender: "F", occupation: "Jobseeker" },
    { content: "Kerja remote enak sih, tapi kesepian banget gak ada temen ngobrol.", topic: "Karir", gender: "M", occupation: "Programmer" },

    // --- ROMANCE / LOVE (20) ---
    { content: "Pacaran 5 tahun ditinggal nikah sama yang baru kenal 5 bulan.", topic: "Asmara", gender: "F", occupation: "Mahasiswa" },
    { content: "Suka sama sahabat sendiri tapi takut ngerusak pertemanan.", topic: "Asmara", gender: "M", occupation: "Mahasiswa" },
    { content: "Ceweku minta putus karena aku belum mapan. Sakit tapi realistis.", topic: "Asmara", gender: "M", occupation: "Freelance" },
    { content: "LDR itu berat di ongkos dan di hati. Kapan ya bisa satu kota?", topic: "Asmara", gender: "F", occupation: "Karyawan" },
    { content: "Istriku selingkuh sama mantannya. Dunia rasanya runtuh.", topic: "Asmara", gender: "M", occupation: "Wiraswasta" },
    { content: "Jomblo 28 tahun, tiap lebaran ditanya 'kapan nikah?' mulu.", topic: "Asmara", gender: "F", occupation: "Guru" },
    { content: "Naksir barista kopi kenangan bawah kantor, tapi gak berani ngajak kenalan.", topic: "Asmara", gender: "M", occupation: "Admin" },
    { content: "Terjebak di toxic relationship, dia manipulatif banget tapi gue sayang.", topic: "Asmara", gender: "F", occupation: "Mahasiswa" },
    { content: "Mantan ngechat minjem duit. Dikasih gak ya?", topic: "Asmara", gender: "NB", occupation: "Karyawan" },
    { content: "Selingkuh itu enak di awal, hancur di akhir. Nyesel gue.", topic: "Asmara", gender: "M", occupation: "PNS" },
    { content: "Gue ghosting orang karena gue insecure, bukan karena dia jelek.", topic: "Asmara", gender: "M", occupation: "Mahasiswa" },
    { content: "Bingung milih antara karir di luar negeri atau nikah sama dia.", topic: "Asmara", gender: "F", occupation: "Architect" },
    { content: "Tinder isinya orang aneh semua, capek swipe kiri.", topic: "Asmara", gender: "F", occupation: "Marketing" },
    { content: "Pacar gue posesif parah, ngecek HP tiap jam.", topic: "Asmara", gender: "M", occupation: "Dokter" },
    { content: "Jatuh cinta sama orang beda agama. Temboknya tinggi banget.", topic: "Asmara", gender: "F", occupation: "Mahasiswa" },
    { content: "Suami gue kecanduan judi slot. Harta abis dijualin.", topic: "Asmara", gender: "F", occupation: "Ibu Rumah Tangga" },
    { content: "Gue jadi pelakor dan gue gak bangga. Gue mau berhenti tapi susah.", topic: "Asmara", gender: "F", occupation: "SPG" },
    { content: "Pura-pura bahagia di depan orang tua, padahal udah putus sebulan lalu.", topic: "Asmara", gender: "M", occupation: "Mahasiswa" },
    { content: "First date fail banget, gue tumpahin kopi ke baju dia.", topic: "Asmara", gender: "M", occupation: "Mahasiswa" },
    { content: "Kangen mantan yang udah nikah. Dosa gak sih?", topic: "Asmara", gender: "F", occupation: "Karyawan" },

    // --- FAMILY / PERSONAL (20) ---
    { content: "Ortu gue cerai pas gue umur 25. Ternyata dampaknya masih kerasa banget.", topic: "Keluarga", gender: "NB", occupation: "Freelance" },
    { content: "Gue anak tunggal dan ngerasa beban harapan ortu berat banget.", topic: "Keluarga", gender: "M", occupation: "Mahasiswa" },
    { content: "Adik gue narkoba, gue bingung harus lapor atau rehab diem-diem.", topic: "Keluarga", gender: "M", occupation: "Karyawan" },
    { content: "Mertua gue ikut campur urusan rumah tangga mulu. Stress.", topic: "Keluarga", gender: "F", occupation: "Ibu Rumah Tangga" },
    { content: "Bapak gue patriarki banget, males pulang ke rumah.", topic: "Keluarga", gender: "F", occupation: "Mahasiswa" },
    { content: "Gue gak mau punya anak (childfree) tapi keluarga besar nuntut terus.", topic: "Keluarga", gender: "F", occupation: "Penulis" },
    { content: "Iri sama temen yang keluarganya harmonis. Rumah gue kayak neraka.", topic: "Keluarga", gender: "M", occupation: "Pelajar" },
    { content: "Gue baru tau gue anak adopsi di umur 22. Shock berat.", topic: "Keluarga", gender: "F", occupation: "Mahasiswa" },
    { content: "Kakak pinjem nama gue buat pinjol, sekarang debt collector nyari gue.", topic: "Keluarga", gender: "M", occupation: "Ojol" },
    { content: "Mau cut off keluarga toxic tapi gak tega ninggalin Ibu.", topic: "Keluarga", gender: "F", occupation: "Karyawan" },
    { content: "Rumah warisan jadi rebutan sampe saudara saling lapor polisi.", topic: "Keluarga", gender: "M", occupation: "Wiraswasta" },
    { content: "Gue ngerasa asing di tengah keluarga sendiri pas lagi kumpul lebaran.", topic: "Keluarga", gender: "NB", occupation: "Seniman" },
    { content: "Ibu gue nuntut gue jadi PNS, padahal gue pengen jadi chef.", topic: "Keluarga", gender: "M", occupation: "Koki" },
    { content: "Hamil di luar nikah dan takut ngasih tau orang tua.", topic: "Keluarga", gender: "F", occupation: "Mahasiswa" },
    { content: "Ayah sakit keras dan tabungan gue udah menipis. Tuhan tolong.", topic: "Keluarga", gender: "M", occupation: "Karyawan" },
    { content: "Gue benci pulang kampung karena selalu dibandingin sama sepupu.", topic: "Keluarga", gender: "F", occupation: "Mahasiswa" },
    { content: "Orang tua gue rasis sama pacar gue. Sedih banget.", topic: "Keluarga", gender: "F", occupation: "Mahasiswa" },
    { content: "Gue tulang punggung keluarga, capek banget harus nanggung 5 nyawa.", topic: "Keluarga", gender: "M", occupation: "Buruh" },
    { content: "Kakak ipar gue genit ke gue. Gue takut ngadu ke kakak.", topic: "Keluarga", gender: "F", occupation: "Mahasiswa" },
    { content: "Keluarga gue religius banget, gue agnostik diem-diem.", topic: "Keluarga", gender: "M", occupation: "Peneliti" },

    // --- RANDOM / FUNNY / THOUGHTS (20) ---
    { content: "Kenapa ya indomie di warkop lebih enak daripada bikin sendiri?", topic: "Random", gender: "M", occupation: "Mahasiswa" },
    { content: "Gue kentut pas lagi presentasi depan klien... mau menghilang aja.", topic: "Random", gender: "M", occupation: "Sales" },
    { content: "Teori konspirasi: Kucing sebenernya alien yang ngawasin kita.", topic: "Random", gender: "NB", occupation: "Pengangguran" },
    { content: "Lagi boker di mall, tisunya habis. Tolong.", topic: "Random", gender: "M", occupation: "Pelajar" },
    { content: "Gue beli gym membership setahun tapi cuma dateng 2 kali.", topic: "Random", gender: "F", occupation: "Karyawan" },
    { content: "Salah kirim stiker 'I Love You' ke grup keluarga. Malu banget.", topic: "Random", gender: "F", occupation: "Mahasiswa" },
    { content: "Tadi gue nyapa orang dikira temen, ternyata orang asing. Awkward.", topic: "Random", gender: "M", occupation: "Pejalan Kaki" },
    { content: "Kenapa sih nyamuk diciptakan? Gak ada faedahnya.", topic: "Random", gender: "F", occupation: "Ibu Rumah Tangga" },
    { content: "Gue pura-pura kesurupan biar gak disuruh maju presentasi.", topic: "Random", gender: "M", occupation: "Siswa" },
    { content: "Iseng nyobain makanan kucing. Rasanya hambar guys.", topic: "Random", gender: "NB", occupation: "Youtuber" },
    { content: "Gue takut badut sampe sekarang. Trauma masa kecil.", topic: "Random", gender: "F", occupation: "Karyawan" },
    { content: "Lupa matiin mic pas zoom meeting, gue lagi nyanyi dangdut.", topic: "Random", gender: "M", occupation: "Mahasiswa" },
    { content: "Gue suka nyium bau bensin. Aneh gak sih?", topic: "Random", gender: "F", occupation: "Siswa" },
    { content: "Mimpi dikejar zombie, bangun-bangun ngos-ngosan beneran.", topic: "Random", gender: "M", occupation: "Penulis" },
    { content: "Gue beli barang gak penting di shopee jam 2 pagi. Khilaf.", topic: "Random", gender: "F", occupation: "Karyawan" },
    { content: "Kalo zombie apocalypse terjadi, gue orang pertama yang mati kayaknya.", topic: "Random", gender: "M", occupation: "Gamer" },
    { content: "Gue baru sadar logo Carrefour itu huruf C.", topic: "Random", gender: "NB", occupation: "Desainer" },
    { content: "Pengen jadi kucing aja, kerjaannya cuma tidur sama makan.", topic: "Random", gender: "F", occupation: "Mahasiswa" },
    { content: "Tadi gue liat hantu di pojokan kamar, tapi gue cuekin soalnya ngantuk.", topic: "Random", gender: "M", occupation: "Satpam" },
    { content: "Gue gak bisa bedain lengkuas sama jahe. Maafkan aku ibu.", topic: "Random", gender: "F", occupation: "Istri Baru" },

    // --- CAMPUS / SCHOOL (20) ---
    { content: "Skripsi gue dicoret-coret edan sama dospem. Pengen nangis darah.", topic: "Pendidikan", gender: "F", occupation: "Mahasiswa" },
    { content: "Gue naksir kating tapi dia udah punya pacar seangkatan. Mundur alon-alon.", topic: "Asmara", gender: "M", occupation: "Mahasiswa" },
    { content: "UKT makin mahal, fasilitas kampus makin jelek. Demo yuk?", topic: "Pendidikan", gender: "M", occupation: "Aktivis Kampus" },
    { content: "Gue joki tugas temen sekelas biar bisa bayar kosan.", topic: "Pendidikan", gender: "M", occupation: "Mahasiswa" },
    { content: "Dospem gue ghosting udah sebulan. Kapan lulus woy.", topic: "Pendidikan", gender: "F", occupation: "Mahasiswa Tingkat Akhir" },
    { content: "Salah masuk jurusan. Gue anak seni terjebak di teknik.", topic: "Pendidikan", gender: "NB", occupation: "Mahasiswa" },
    { content: "Temen kelompok gak ada yang kerja, gue ngecarry sendirian.", topic: "Pendidikan", gender: "F", occupation: "Mahasiswa" },
    { content: "Gue nyontek pas UAS dan ketahuan pengawas. Mampus gue.", topic: "Pendidikan", gender: "M", occupation: "Mahasiswa" },
    { content: "IPK gue nasakom (nasib satu koma). Malu sama ortu.", topic: "Pendidikan", gender: "M", occupation: "Mahasiswa Abadi" },
    { content: "Organisasi kampus toxic banget, senioritasnya gila.", topic: "Pendidikan", gender: "F", occupation: "Mahasiswa Baru" },
    { content: "Gue diem-diem suka tidur di perpus kampus karena adem.", topic: "Pendidikan", gender: "M", occupation: "Mahasiswa" },
    { content: "Wisuda online itu gak berasa wisudanya. Sedih angkatan corona.", topic: "Pendidikan", gender: "F", occupation: "Alumni" },
    { content: "Gue nembak cewek di kantin dan ditolak depan banyak orang.", topic: "Asmara", gender: "M", occupation: "Mahasiswa" },
    { content: "Smester depan mau cuti, depresi berat gara-gara tugas.", topic: "Kesehatan Mental", gender: "NB", occupation: "Mahasiswa" },
    { content: "Kostan gue angker, sering ada suara nangis malem-malem.", topic: "Horor", gender: "F", occupation: "Mahasiswa" },
    { content: "Uang bulanan abis buat hedon, sekarang makan promag.", topic: "Keuangan", gender: "M", occupation: "Mahasiswa" },
    { content: "Gue baru tau temen sekelas gue ternyata anak rektor.", topic: "Pendidikan", gender: "F", occupation: "Mahasiswa" },
    { content: "Presentasi pake bahasa inggris, gue keringet dingin satu ember.", topic: "Pendidikan", gender: "M", occupation: "Mahasiswa" },
    { content: "Gue ngerjain tugas H-1 jam deadline. The power of kepepet.", topic: "Pendidikan", gender: "M", occupation: "Mahasiswa" },
    { content: "Lulus kumlaude tapi nganggur setahun. Hidup itu keras.", topic: "Karir", gender: "F", occupation: "Jobseeker" }
];

const SEED_POSTS = RAW_SEED_POSTS.map((seed, idx) => {
    // Generate a fixed anchor date so that it looks realistic but remains completely static across page refreshes
    const anchorDate = new Date('2025-12-01T08:00:00Z');
    anchorDate.setHours(anchorDate.getHours() - (idx * 17)); // Spread them out

    return {
        ...seed,
        post_id: `seed_post_${idx}`,
        created_at: anchorDate,
        likes: (seed.content.length * 7) % 50 // deterministic likes
    };
});

module.exports = { SEED_POSTS };
